/**
 * Web3 (ethers.js) connectivity to the BlackSwanOS contract on Base.
 *
 * Uses the ABI dynamically generated by `npx hardhat compile` (Phase 1),
 * copied into ./abi/BlackSwanOS.json — never a hand-maintained ABI.
 */

import { dirname, join } from "node:path";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { ethers } from "ethers";
import { config } from "./config.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const abiPath = join(__dirname, "..", "abi", "BlackSwanOS.json");

export const escrowAbi = JSON.parse(readFileSync(abiPath, "utf-8"));

const erc20Abi = [
  "function approve(address spender, uint256 amount) returns (bool)",
  "function allowance(address owner, address spender) view returns (uint256)",
  "function balanceOf(address account) view returns (uint256)",
];

export const provider = new ethers.JsonRpcProvider(
  config.rpcUrl,
  config.chainId
);

/** Agent wallet this MCP server instance signs transactions on behalf of. */
export const wallet = new ethers.Wallet(config.agentPrivateKey, provider);

/** Write-capable contract instance (signs with the agent wallet). */
export const escrowContract = new ethers.Contract(
  config.contractAddress,
  escrowAbi,
  wallet
);

/** Read-only contract instance (no signer required for view calls). */
export const escrowContractReadOnly = new ethers.Contract(
  config.contractAddress,
  escrowAbi,
  provider
);

export const usdcContract = new ethers.Contract(
  config.usdcAddress,
  erc20Abi,
  wallet
);

/**
 * Mirrors BlackSwanOS.sol `EscrowState` enum ordering exactly.
 * NOTE: the unused `AWAITING_BUYER` state was removed from the contract
 * (security audit cleanup) — `AWAITING_SELLER` is now index 0.
 */
export const ESCROW_STATE_NAMES = [
  "AWAITING_SELLER",
  "LOCKED",
  "DISPUTED",
  "RESOLVED",
  "CLAIMED",
] as const;

/** Mirrors BlackSwanOS.sol `DisputeOutcome` enum ordering exactly. */
export const DISPUTE_OUTCOME_NAMES = [
  "NONE",
  "SELLER_CHEATED",
  "BUYER_CHEATED",
  "SELLER_VALID",
] as const;
